# Numpy

以下の設問に回答し、Google Classroom で提出してください。なお、提出の際はファイル名を以下のように変更すること

■ ファイル名
- 学籍番号_氏名_Math_Ex13.ipynb

In [1]:
import numpy as np

Ex.01：以下のプログラムを作成してください

1. Numpy の ndarray 型で ベクトル $\begin{bmatrix} 10 & 20 & 30 \end{bmatrix}$ のデータを変数 x として作成する
1. 変数 x の内容を出力する
1. 変数 x のデータ型を出力する
1. 変数 x の次元数を出力する
1. 変数 x の行列の構造を出力する

In [2]:
x = np.array([10, 20, 30])
print(x)            # 内容の表示
print(x.dtype)      # データ型の表示
print(x.ndim)       # 次元数の表示
print(x.shape)      # 行列の構造を表示

[10 20 30]
int32
1
(3,)


Ex.02：以下のプログラムを作成してください

1. Numpy の ndarray 型で 行列 $\begin{bmatrix}
10 & 20 & 30 \\
40 & 50 & 60 \\
\end{bmatrix}$ のデータを変数 x として作成する
1. 変数 x の内容を出力する
1. 変数 x のデータ型を出力する
1. 変数 x の次元数を出力する
1. 変数 x の行列の構造を出力する

In [3]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60]
  ])
print(x)            # 内容の表示
print(x.dtype)      # データ型の表示
print(x.ndim)       # 次元数の表示
print(x.shape)      # 行列の構造を表示

[[10 20 30]
 [40 50 60]]
int32
2
(2, 3)


Ex.03：以下のプログラムを作成してください

1. 行列の構造が (1, 2, 3) となるような 3 次元のテンソルを変数 x として作成する。なお、データの内容は問わない
1. 変数 x の内容を出力する
1. 変数 x のデータ型を出力する
1. 変数 x の次元数を出力する
1. 変数 x の行列の構造を出力する

In [4]:
x = np.array([
    [
      [11, 12, 13], 
      [21, 22, 23]
    ]
  ])
print(x)            # 内容の表示
print(x.dtype)      # データ型の表示
print(x.ndim)       # 次元数の表示
print(x.shape)      # 行列の構造を表示

[[[11 12 13]
  [21 22 23]]]
int32
3
(1, 2, 3)


Ex.04：以下のプログラムを作成してください

1. 行列の構造が (1, 2, 3) となるような 3 次元のテンソルを変数 x として作成する。なお、データの内容は問わない
1. x の内容を転置し、再度 x に代入する
1. 変数 x の内容を出力する
1. 変数 x のデータ型を出力する
1. 変数 x の次元数を出力する
1. 変数 x の行列の構造を出力する

In [5]:
x = np.array([
    [
      [11, 12, 13], 
      [21, 22, 23]
    ]
  ])
x = x.T

print(x)            # 内容の表示
print(x.dtype)      # データ型の表示
print(x.ndim)       # 次元数の表示
print(x.shape)      # 行列の構造を表示

[[[11]
  [21]]

 [[12]
  [22]]

 [[13]
  [23]]]
int32
3
(3, 2, 1)


Ex.05：以下のプログラムを作成してください

1. Numpy の ndarray 型で ベクトル $\begin{bmatrix} 10 & 20 & 30 \end{bmatrix}$ のデータを変数 x1 として作成する
1. Numpy の ndarray 型で ベクトル $\begin{bmatrix} 40 & 50 & 60 \end{bmatrix}$ のデータを変数 x2 として作成する
1. 変数 x1 と x2 を加算し、Numpy の ndarray 型の変数 y に代入する
1. 変数 y の内容を出力する
1. 変数 y のデータ型を出力する
1. 変数 y の次元数を出力する
1. 変数 y の行列の構造を出力する

In [6]:
x1 = np.array([10, 20, 30])
x2 = np.array([40, 50, 60])
y = np.array(x1 + x2)

print(y)            # 内容の表示
print(y.dtype)      # データ型の表示
print(y.ndim)       # 次元数の表示
print(y.shape)      # 行列の構造を表示

[50 70 90]
int32
1
(3,)


Ex.06：以下のプログラムを作成してください

1. Numpy の ndarray 型で 行列 $\begin{bmatrix}
11 & 12 \\
21 & 22 \\
\end{bmatrix}$ のデータを変数 x として作成する
1. x の要素を 10 倍し、変数 y に格納する
1. 変数 y の内容を出力する
1. 変数 y のデータ型を出力する
1. 変数 y の次元数を出力する
1. 変数 y の行列の構造を出力する

In [7]:
x = np.array([
    [11, 12],
    [21, 22]
  ])
y = x * 10

print(y)            # 内容の表示
print(y.dtype)      # データ型の表示
print(y.ndim)       # 次元数の表示
print(y.shape)      # 行列の構造を表示

[[110 120]
 [210 220]]
int32
2
(2, 2)


Ex.07：以下のプログラムを作成してください

1. Numpy の ndarray 型で ベクトル $\begin{bmatrix} 10 & 20 & 30 \end{bmatrix}$ のデータを変数 x1 として作成する
2. Numpy の ndarray 型で ベクトル $\begin{bmatrix} 40 & 50 & 60 \end{bmatrix}$ のデータを変数 x2 として作成する
3. 変数 x1 と x2 内積を計算し Numpy の ndarray 型の変数 y に代入する
4. 変数 y の内容を出力する
5. 変数 y のデータ型を出力する
6. 変数 y の次元数を出力する
7. 変数 y の行列の構造を出力する

In [8]:
x1 = np.array([10, 20, 30])
x2 = np.array([40, 50, 60])
y = np.array(x1 @ x2)
# y = x1.dot(x2)

print(y)            # 内容の表示
print(y.dtype)      # データ型の表示
print(y.ndim)       # 次元数の表示
print(y.shape)      # 行列の構造を表示

3200
int32
0
()


Ex.08：以下のプログラムを作成してください

1. 以下の条件の乱数を変数 x として作成する
- 0 ～ 1 までの一様分布を持つ
- 2 x 3 x 5 の行列のから成る
- seed は 1 とする
2. 変数 x の内容を出力する

In [9]:
np.random.seed(seed=1)
x = np.random.rand(2, 3, 5)     # 2 x 3 x 5 の行列の生成
print(x)

[[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
   1.46755891e-01]
  [9.23385948e-02 1.86260211e-01 3.45560727e-01 3.96767474e-01
   5.38816734e-01]
  [4.19194514e-01 6.85219500e-01 2.04452250e-01 8.78117436e-01
   2.73875932e-02]]

 [[6.70467510e-01 4.17304802e-01 5.58689828e-01 1.40386939e-01
   1.98101489e-01]
  [8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01
   8.76389152e-01]
  [8.94606664e-01 8.50442114e-02 3.90547832e-02 1.69830420e-01
   8.78142503e-01]]]


Ex.09：以下のプログラムを作成してください

1. 以下の条件の連続値を変数 x として作成する
- 値は 0 ～ 180 とする
- 値の間隔は 10 とする
- 要素数は 19 個とする
- arange 関数を使用する
2. 変数 x の内容を出力する

In [10]:
x = np.arange(0, 181, 10)
print(x)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180]


Ex.10：以下のプログラムを作成してください

1. 以下の条件の連続値を変数 x として作成する
- 値は 0 ～ 180 とする
- 値の間隔は 10 とする
- 要素数は 19 個とする
- linspace 関数を使用する
2. 変数 x の内容を出力する

In [11]:
x = np.linspace(0, 180, 19)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120. 130.
 140. 150. 160. 170. 180.]
